# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/dragomir/repos/NES_Nexys_A7/Nexys_A7_NES/src/NEXYS_A7.xdc

# IP: ip/chr_8_rom/chr_8_rom.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==chr_8_rom || ORIG_REF_NAME==chr_8_rom} -quiet] -quiet

# IP: ip/prg_16_rom/prg_16_rom.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==prg_16_rom || ORIG_REF_NAME==prg_16_rom} -quiet] -quiet
