# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/dragomir/repos/NES_Nexys_A7/Nexys_A7_NES/Nexys_A7_NES.srcs/sources_1/ip/vram/vram.xci
# IP: The module: 'vram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/dragomir/repos/NES_Nexys_A7/Nexys_A7_NES/Nexys_A7_NES.gen/sources_1/ip/vram/vram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'vram'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/dragomir/repos/NES_Nexys_A7/Nexys_A7_NES/Nexys_A7_NES.srcs/sources_1/ip/vram/vram.xci
# IP: The module: 'vram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/dragomir/repos/NES_Nexys_A7/Nexys_A7_NES/Nexys_A7_NES.gen/sources_1/ip/vram/vram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'vram'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
